### ISSUE TITLE
TBx0108 max voltage on "B" side... or breaking out "VM" for higher voltages

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/Edison_H-Bridge_Block#1]
I think it might be worth noting that the max voltage you can supply on VIN is 5.5V, or else you are going outside the max voltage on the "B" side of the logic conversion chip. 

I was working on the testbed for this, and was worried that 5.5V may only light up the LEDs very dimly (a pain to test visually in production). We could think about reducing the values for R1 and R2, or we could think about breaking out VM, to allow for higher voltages to your motors (while still keeping the logic level within the TBX0108 chips specs)

**Comment by ToniCorinne** [comment]
Closing out this issue as there do not appear to be any customer complaints about this currently.
